/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TwoFactorRouteImport } from './routes/two-factor'
import { Route as AdminOrganizationsRouteImport } from './routes/admin/organizations'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as CoursesSlugRouteImport } from './routes/courses/$slug'
import { Route as LearningIndexRouteImport } from './routes/learning/index'
import { Route as WorkspaceSettingsRouteImport } from './routes/workspace/settings'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as LearningSlugLessonIdRouteImport } from './routes/learning/$slug/$lessonId'
import { Route as WorkspaceCoursesIndexRouteImport } from './routes/workspace/courses/index'
import { Route as WorkspaceCoursesCourseIdRouteImport } from './routes/workspace/courses/$courseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TwoFactorRoute = TwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/admin/organizations',
  path: '/admin/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningIndexRoute = LearningIndexRouteImport.update({
  id: '/learning/',
  path: '/learning/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSettingsRoute = WorkspaceSettingsRouteImport.update({
  id: '/workspace/settings',
  path: '/workspace/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningSlugLessonIdRoute = LearningSlugLessonIdRouteImport.update({
  id: '/learning/$slug/$lessonId',
  path: '/learning/$slug/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceCoursesIndexRoute = WorkspaceCoursesIndexRouteImport.update({
  id: '/workspace/courses/',
  path: '/workspace/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceCoursesCourseIdRoute =
  WorkspaceCoursesCourseIdRouteImport.update({
    id: '/workspace/courses/$courseId',
    path: '/workspace/courses/$courseId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/two-factor': typeof TwoFactorRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/workspace/settings': typeof WorkspaceSettingsRoute
  '/courses/': typeof CoursesIndexRoute
  '/learning/': typeof LearningIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/learning/$slug/$lessonId': typeof LearningSlugLessonIdRoute
  '/workspace/courses/$courseId': typeof WorkspaceCoursesCourseIdRoute
  '/workspace/courses/': typeof WorkspaceCoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/two-factor': typeof TwoFactorRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/workspace/settings': typeof WorkspaceSettingsRoute
  '/courses': typeof CoursesIndexRoute
  '/learning': typeof LearningIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/learning/$slug/$lessonId': typeof LearningSlugLessonIdRoute
  '/workspace/courses/$courseId': typeof WorkspaceCoursesCourseIdRoute
  '/workspace/courses': typeof WorkspaceCoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/two-factor': typeof TwoFactorRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/workspace/settings': typeof WorkspaceSettingsRoute
  '/courses/': typeof CoursesIndexRoute
  '/learning/': typeof LearningIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/learning/$slug/$lessonId': typeof LearningSlugLessonIdRoute
  '/workspace/courses/$courseId': typeof WorkspaceCoursesCourseIdRoute
  '/workspace/courses/': typeof WorkspaceCoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/two-factor'
    | '/admin/organizations'
    | '/admin/users'
    | '/courses/$slug'
    | '/workspace/settings'
    | '/courses/'
    | '/learning/'
    | '/api/auth/$'
    | '/learning/$slug/$lessonId'
    | '/workspace/courses/$courseId'
    | '/workspace/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/two-factor'
    | '/admin/organizations'
    | '/admin/users'
    | '/courses/$slug'
    | '/workspace/settings'
    | '/courses'
    | '/learning'
    | '/api/auth/$'
    | '/learning/$slug/$lessonId'
    | '/workspace/courses/$courseId'
    | '/workspace/courses'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/two-factor'
    | '/admin/organizations'
    | '/admin/users'
    | '/courses/$slug'
    | '/workspace/settings'
    | '/courses/'
    | '/learning/'
    | '/api/auth/$'
    | '/learning/$slug/$lessonId'
    | '/workspace/courses/$courseId'
    | '/workspace/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TwoFactorRoute: typeof TwoFactorRoute
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  WorkspaceSettingsRoute: typeof WorkspaceSettingsRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  LearningIndexRoute: typeof LearningIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  LearningSlugLessonIdRoute: typeof LearningSlugLessonIdRoute
  WorkspaceCoursesCourseIdRoute: typeof WorkspaceCoursesCourseIdRoute
  WorkspaceCoursesIndexRoute: typeof WorkspaceCoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/two-factor': {
      id: '/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof TwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/admin/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/': {
      id: '/learning/'
      path: '/learning'
      fullPath: '/learning/'
      preLoaderRoute: typeof LearningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/settings': {
      id: '/workspace/settings'
      path: '/workspace/settings'
      fullPath: '/workspace/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/$slug/$lessonId': {
      id: '/learning/$slug/$lessonId'
      path: '/learning/$slug/$lessonId'
      fullPath: '/learning/$slug/$lessonId'
      preLoaderRoute: typeof LearningSlugLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/courses/': {
      id: '/workspace/courses/'
      path: '/workspace/courses'
      fullPath: '/workspace/courses/'
      preLoaderRoute: typeof WorkspaceCoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/courses/$courseId': {
      id: '/workspace/courses/$courseId'
      path: '/workspace/courses/$courseId'
      fullPath: '/workspace/courses/$courseId'
      preLoaderRoute: typeof WorkspaceCoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TwoFactorRoute: TwoFactorRoute,
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminUsersRoute: AdminUsersRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  WorkspaceSettingsRoute: WorkspaceSettingsRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  LearningIndexRoute: LearningIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  LearningSlugLessonIdRoute: LearningSlugLessonIdRoute,
  WorkspaceCoursesCourseIdRoute: WorkspaceCoursesCourseIdRoute,
  WorkspaceCoursesIndexRoute: WorkspaceCoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
